scrape_configs:
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - 58.87.72.90:8080
  # - job_name: 'prometheus'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['localhost:9090']
  - job_name: 'mysql'
    static_configs:
      - targets: ['58.87.72.90:9104']
  - job_name: 'linux'
    static_configs:
      - targets: ['58.87.72.90:9100']
        labels:
          instance: node1
